### ISSUE TITLE
Registering an Application

### ISSUE THREAD

**Issue by mcschatz** [mcschatz/traffic_spy#1]
As a user:
when I submit a POST request to "/sources"
with an identifier set to "jumpstartlab"
and a "rootUrl" set to "http://jumpstartlab.com"
then I should receive a response of 200 OK
and a response body of  "{"identifier":"jumpstartlab"}" 

When I submit a POST request to "/sources"
and I am missing an "identifier" and "rootUrl"
Then I should receive response of 400 Bad Request

When I submit a POST request to "/sources"
With an "identifier" of "jumpstartlab"
And the "identifier" has already been taken
Then I should receive response of 403 Forbidden
And I should receive a descriptive error message

**Comment by MowAlon** [comment]
I can totally see this

**Comment by Kealii** [comment]
I can also see this

**Comment by Kealii** [comment]
Functionally complete, Needs refactor

**Comment by mcschatz** [comment]
YA HOO! First card finished
