### ISSUE TITLE
Processing Requests

### ISSUE THREAD

**Issue by Kealii** [mcschatz/traffic_spy#4]
As a user:
When I submit a POST request to '/data'
With an identifier set to 'jumpstartlab'
And a valid payload for a registered user
Then I should receive a '200 OK'

When I submit a POST request to '/data'
And missing a payload
Then I should  a receive a '400 Bad Request'
And receive the error 'Missing Payload'

When  I submit a POST request to '/data'
And the exact payload already exists
Then I should receive a '403 Forbidden'
And receive the error 'This request has already been recorded'

When I submit a POST request to '/data'
And the application URL does not exist
Then I should receive a '403 Forbidden'
And receive the error 'Application not registered'

**Comment by mcschatz** [comment]
successful request completed
