### ISSUE TITLE
Application Details

### ISSUE THREAD

**Issue by jbrr** [mcschatz/traffic_spy#7]
As a user,
when I visit '/sources/IDENTIFIER',
And the 'IDENTIFIER' is registered,
Then I should see the following statistics:
*Most requested URLs to least requested URLS
*Web browser breakdown across all requests
*OS breakdown across all requests
*Screen resolution across all requests (Width x Height)
*Longest average response time per URL to shortest average response time per URL
*Hyperlinks to each URL to view URL specific data
*Hyperlink to view aggregate event data
When I visit '/sources/IDENTIFIER',
And the 'IDENTIFIER' is not registered,
Then I should get a message that the 'IDENTIFIER' does not exist.

**Comment by jbrr** [comment]
Er, shoot, I titled this wrong. I guess it should be "Application Details"

**Comment by MowAlon** [comment]
Title corrected via GitHub

**Comment by MowAlon** [comment]
We put this one to bed. Booyah.
